"""Generate flashcards_db/init/02_seed.sql from the OpenStax corpus index.

Deterministic: same book_map.json in, byte-identical SQL out (no timestamps).
Run from repo root:  python tools/generate_flashcards_seed.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BOOK_MAP = REPO / "references" / "openstax_calculus_v1" / "book_map.json"
OUT = REPO / "flashcards_db" / "init" / "02_seed.sql"

SUBJECT_NAME = "Calculus"


def sql_str(s):
    """Escape a Python string as a single-quoted MySQL literal."""
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def lo_index(book):
    """(section_number, lo_text) -> learning_objective id, 1-based in book order.

    Shared with tools/import_concept_flashcards.py so both generators agree.
    """
    index = {}
    lo_id = 0
    for sec in book["sections"]:
        for lo in sec["learning_objectives"]:
            lo_id += 1
            index[(sec["number"], lo)] = lo_id
    return index


def main():
    book = json.loads(BOOK_MAP.read_text(encoding="utf-8"))
    lines = [
        "-- GENERATED by tools/generate_flashcards_seed.py. Do not edit by hand.",
        "-- Source: references/openstax_calculus_v1/book_map.json",
        "USE flashcards;",
        "SET NAMES utf8mb4;",
        "",
        f"INSERT INTO subject (id, name) VALUES (1, {sql_str(SUBJECT_NAME)});",
        "",
        "INSERT INTO textbook (id, subject_id, title, book_key, authors, license,"
        " attribution, source_url) VALUES",
        "  (1, 1, {t}, {k}, {a}, {l}, {at}, {u});".format(
            t=sql_str(book["title"]),
            k=sql_str(book["book_key"]),
            a=sql_str("; ".join(book["authors"])),
            l=sql_str(book["license"]),
            at=sql_str(book["attribution_required"]),
            u=sql_str(book["source_url"]),
        ),
        "",
    ]

    index = lo_index(book)
    chapter_rows, lo_rows = [], []
    lo_id = 0
    for ch_id, sec in enumerate(book["sections"], start=1):
        chap_num = int(sec["number"].split(".")[0])
        chapter_rows.append(
            f"  ({ch_id}, 1, {chap_num}, {sql_str(sec['number'])},"
            f" {sql_str(sec['title'])})"
        )
        for ordinal, lo in enumerate(sec["learning_objectives"], start=1):
            lo_id = index[(sec["number"], lo)]
            lo_rows.append(f"  ({lo_id}, {ch_id}, {sql_str(lo)}, {ordinal})")

    lines.append(
        "INSERT INTO chapter (id, textbook_id, chapter_number, section_number, name)"
        " VALUES\n" + ",\n".join(chapter_rows) + ";"
    )
    lines.append("")
    lines.append(
        "INSERT INTO learning_objective (id, chapter_id, lo_text, ordinal) VALUES\n"
        + ",\n".join(lo_rows) + ";"
    )
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"chapters={len(chapter_rows)} los={lo_id}")
    assert len(chapter_rows) == 45, "corpus changed: update spec expectations"


if __name__ == "__main__":
    main()
